### ISSUE TITLE
Compress images during collectstatic ?

### ISSUE THREAD

**Issue by stuaxo** [samastur/image-diet#4]
It would be good if image-diet could work from collectstatic.

Not sure if this is the best place, or maybe integration with something like django-pipeline would be better ?

**Comment by samastur** [comment]
Image-diet2 (https://github.com/samastur/image-diet2/) is now implemented as a storage mixin that can be used with other Django storage backends with DietStorage automatically binding to the currently configured storage backend.

image-diet itself will not receive further development.
